### ISSUE TITLE
Not working on Xcode11

### ISSUE THREAD

**Issue by thandang** [CanalTP/NavitiaSDKUX_ios#348]
I'm not be able build the project on Xcode11 if I integrate NavitiaSDKUI to my iOS (Swift project)
`2.	While running pass #0 SILModuleTransform "SerializeSILPass".
3.	While serializing 'journeys' (at /<path to project>sources/afc-easytick-ios-app/Pods/NavitiaSDKUI/NavitiaSDKUI/Scenes/ListJourneys/ListJourneysModels.swift:48:16)
0  swift                    0x000000010ae06a13 PrintStackTraceSignalHandler(void*) + 51
1  swift                    0x000000010ae061e6 SignalHandler(int) + 358
2  libsystem_platform.dylib 0x00007fff62229b5d _sigtramp + 29
3  libsystem_platform.dylib 0x00007ffee9242510 _sigtramp + 2265024976
4  swift                    0x0000000107951841 swift::ParamDecl::getDefaultValueStringRepresentation(llvm::SmallVectorImpl<char>&) const + 1201
5  swift                    0x00000001076d898a swift::serialization::Serializer::writeDecl(swift::Decl const*) + 5946
6  swift                    0x00000001076fe42f swift::serialization::Serializer::writeAllDeclsAndTypes() + 62287
7  swift                    0x000000010770b3f4 swift::serialization::Serializer::writeAST(llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, bool) + 5364
8  swift                    0x0000000107718330 swift::serialization::Serializer::writeToStream(llvm::raw_ostream&, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::SILModule const*, swift::SerializationOptions const&) + 6016
9  swift                    0x0000000107719c0b bool llvm::function_ref<bool (llvm::raw_pwrite_stream&)>::callback_fn<swift::serialize(llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::SerializationOptions const&, swift::SILModule const*)::$_8>(long, llvm::raw_pwrite_stream&) + 139
10 swift                    0x0000000106a20729 swift::withOutputFile(swift::DiagnosticEngine&, llvm::StringRef, llvm::function_ref<bool (llvm::raw_pwrite_stream&)>) + 2569
11 swift                    0x0000000107719a67 swift::serialize(llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::SerializationOptions const&, swift::SILModule const*) + 311
12 swift                    0x0000000106a5c1bb std::__1::__function::__func<performCompileStepsPostSILGen(swift::CompilerInstance&, swift::CompilerInvocation&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, bool, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, bool, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*)::$_12, std::__1::allocator<performCompileStepsPostSILGen(swift::CompilerInstance&, swift::CompilerInvocation&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, bool, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, bool, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*)::$_12>, void ()>::operator()() + 603
13 swift                    0x0000000107203c61 SerializeSILPass::run() + 49
14 swift                    0x00000001070fa129 swift::SILPassManager::execute() + 7305
15 swift                    0x0000000106d56c0b swift::CompilerInstance::performSILProcessing(swift::SILModule*, swift::UnifiedStatsReporter*) + 1563
16 swift                    0x0000000106a52375 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 33925
17 swift                    0x0000000106a466e4 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 6820
18 swift                    0x00000001069d3be3 main + 1219`

**Comment by MikePetitfils** [comment]
Hi Than, thanks for your feedback!

The xcode update 11.3 solves this issue.

Best regards,
